In [315]:
import pandas as pd
import numpy as np

In [342]:
df = pd.read_csv('data/survey_results_public.csv')

## Modifying row and columns data

In [343]:
df.head(2)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

## changing column name

In [344]:
# will change the column name in the df_copy dataframe
df_copy = df.copy(deep=True)

In [345]:
df_copy.rename(columns={'respondent': 'indexNo'}, inplace=True)
df_copy.head(1)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [346]:
# make change in all the column name, have to iterate over the column names

df_copy.columns = [x.lower() for x in df.columns]

In [347]:
df_copy.columns

Index(['respondent', 'mainbranch', 'hobbyist', 'opensourcer', 'opensource',
       'employment', 'country', 'student', 'edlevel', 'undergradmajor',
       'eduother', 'orgsize', 'devtype', 'yearscode', 'age1stcode',
       'yearscodepro', 'careersat', 'jobsat', 'mgridiot', 'mgrmoney',
       'mgrwant', 'jobseek', 'lasthiredate', 'lastint', 'fizzbuzz',
       'jobfactors', 'resumeupdate', 'currencysymbol', 'currencydesc',
       'comptotal', 'compfreq', 'convertedcomp', 'workweekhrs', 'workplan',
       'workchallenge', 'workremote', 'workloc', 'impsyn', 'coderev',
       'coderevhrs', 'unittests', 'purchasehow', 'purchasewhat',
       'languageworkedwith', 'languagedesirenextyear', 'databaseworkedwith',
       'databasedesirenextyear', 'platformworkedwith',
       'platformdesirenextyear', 'webframeworkedwith',
       'webframedesirenextyear', 'misctechworkedwith',
       'misctechdesirenextyear', 'devenviron', 'opsys', 'containers',
       'blockchainorg', 'blockchainis', 'betterlife', 'itperson', 'offon',
       'socialmedia', 'extraversion', 'screenname', 'sovisit1st',
       'sovisitfreq', 'sovisitto', 'sofindanswer', 'sotimesaved',
       'sohowmuchtime', 'soaccount', 'sopartfreq', 'sojobs', 'entteams',
       'socomm', 'welcomechange', 'sonewcontent', 'age', 'gender', 'trans',
       'sexuality', 'ethnicity', 'dependents', 'surveylength', 'surveyease'],
      dtype='object')

## change columns values

In [348]:
df_copy.loc[0, 'mainbranch'] = ('I AM STUDENT')

In [349]:
df_copy.head(1)

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,welcomechange,sonewcontent,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease
0,1,I AM STUDENT,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [350]:
# in first row change the column 'mainbranch' value to lower
df_copy['mainbranch'] = df_copy.loc[0, 'mainbranch'].lower()

In [351]:
df_copy.head(2)

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,welcomechange,sonewcontent,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease
0,1,i am student,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,i am student,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

## map()

In [352]:
# change yes to True and No to False
df_copy['hobbyist'] = df_copy['hobbyist'].map({'Yes': True, 'No': False})

In [353]:
df_copy.head(2)

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,welcomechange,sonewcontent,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease
0,1,i am student,True,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,i am student,False,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

## add or remove row and column from dataframe

## adding columns

In [354]:
# adding column to the dataframe
df_copy['added_column'] = 'NaN'

In [355]:
# if you check in the last 'added_column' was added
df_copy.columns

Index(['respondent', 'mainbranch', 'hobbyist', 'opensourcer', 'opensource',
       'employment', 'country', 'student', 'edlevel', 'undergradmajor',
       'eduother', 'orgsize', 'devtype', 'yearscode', 'age1stcode',
       'yearscodepro', 'careersat', 'jobsat', 'mgridiot', 'mgrmoney',
       'mgrwant', 'jobseek', 'lasthiredate', 'lastint', 'fizzbuzz',
       'jobfactors', 'resumeupdate', 'currencysymbol', 'currencydesc',
       'comptotal', 'compfreq', 'convertedcomp', 'workweekhrs', 'workplan',
       'workchallenge', 'workremote', 'workloc', 'impsyn', 'coderev',
       'coderevhrs', 'unittests', 'purchasehow', 'purchasewhat',
       'languageworkedwith', 'languagedesirenextyear', 'databaseworkedwith',
       'databasedesirenextyear', 'platformworkedwith',
       'platformdesirenextyear', 'webframeworkedwith',
       'webframedesirenextyear', 'misctechworkedwith',
       'misctechdesirenextyear', 'devenviron', 'opsys', 'containers',
       'blockchainorg', 'blockchainis', 'betterlife', 'itperson', 'offon',
       'socialmedia', 'extraversion', 'screenname', 'sovisit1st',
       'sovisitfreq', 'sovisitto', 'sofindanswer', 'sotimesaved',
       'sohowmuchtime', 'soaccount', 'sopartfreq', 'sojobs', 'entteams',
       'socomm', 'welcomechange', 'sonewcontent', 'age', 'gender', 'trans',
       'sexuality', 'ethnicity', 'dependents', 'surveylength', 'surveyease',
       'added_column'],
      dtype='object')

## split() and sign to columns

In [369]:
# spliting the 'welcomechange' values by 'as'  
# we are using expand=True to seperate into two columns
# we will assing this two column in Striaght and Home 

df_copy[['Straight', 'Homo']] = df_copy['sexuality'].str.split('/', expand=True).head()

In [370]:
df_copy.head(2)

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
6391,6417.0,i am student,1.0,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,...,NaN,NaN,NaN,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
73920,74386.0,i am student,1.0,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Afghanistan,"Yes, part-time",Associate degree,"Information systems, information technology, o...",...,23.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy,Straight,Heterosexual

## drop()  -> columns

In [358]:
# to apply this change in the dataFrame we need to ue inplace
df_copy.drop(columns=['added_column'], inplace=True)

In [359]:
df_copy.columns

Index(['respondent', 'mainbranch', 'hobbyist', 'opensourcer', 'opensource',
       'employment', 'country', 'student', 'edlevel', 'undergradmajor',
       'eduother', 'orgsize', 'devtype', 'yearscode', 'age1stcode',
       'yearscodepro', 'careersat', 'jobsat', 'mgridiot', 'mgrmoney',
       'mgrwant', 'jobseek', 'lasthiredate', 'lastint', 'fizzbuzz',
       'jobfactors', 'resumeupdate', 'currencysymbol', 'currencydesc',
       'comptotal', 'compfreq', 'convertedcomp', 'workweekhrs', 'workplan',
       'workchallenge', 'workremote', 'workloc', 'impsyn', 'coderev',
       'coderevhrs', 'unittests', 'purchasehow', 'purchasewhat',
       'languageworkedwith', 'languagedesirenextyear', 'databaseworkedwith',
       'databasedesirenextyear', 'platformworkedwith',
       'platformdesirenextyear', 'webframeworkedwith',
       'webframedesirenextyear', 'misctechworkedwith',
       'misctechdesirenextyear', 'devenviron', 'opsys', 'containers',
       'blockchainorg', 'blockchainis', 'betterlife', 'itperson', 'offon',
       'socialmedia', 'extraversion', 'screenname', 'sovisit1st',
       'sovisitfreq', 'sovisitto', 'sofindanswer', 'sotimesaved',
       'sohowmuchtime', 'soaccount', 'sopartfreq', 'sojobs', 'entteams',
       'socomm', 'welcomechange', 'sonewcontent', 'age', 'gender', 'trans',
       'sexuality', 'ethnicity', 'dependents', 'surveylength', 'surveyease',
       'Straight', 'Homo'],
      dtype='object')

## adding single row

In [373]:
# appending row at the end 
# only the column that we assign that will have a value reset all the column will be NaN 

df_copy = df_copy.append({'mainbranch': 'I am not student'}, ignore_index=True)

In [374]:
df_copy.tail()

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
88880,85744.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88062.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88601.0,i am student,0.0,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88883,NaN,I am not student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88884,NaN,I am not student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## drop()  -> row

In [375]:
# deleting the row
df_copy.drop(index=88882)

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
0,6417.0,i am student,1.0,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,...,NaN,NaN,NaN,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
1,74386.0,i am student,1.0,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Afghanistan,"Yes, part-time",Associate degree,"Information systems, information technology, o...",...,23.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy,Straight,Heterosexual
2,7085.0,i am student,1.0,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
3,28638.0,i am student,1.0,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN,NaN,NaN
4,50767.0,i am student,0.0,Less than once per year,NaN,"Independent contractor, freelancer, or self-em...",Afghanistan,"Yes, part-time",Associate degree,"A health science (ex. nursing, pharmacy, radio...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88879,83648.0,i am student,0.0,Never,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,85744.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88062.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88883,NaN,I am not student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88884,NaN,I am not student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Sorting data


## sort_values()

In [376]:
# it will sort value by ascending order
df_copy.sort_values(by=['country', 'employment'], ascending=True, inplace=True)
df_copy.head(2)

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
0,6417.0,i am student,1.0,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,...,NaN,NaN,NaN,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
23,88582.0,i am student,1.0,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...",...,32.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult,NaN,NaN

In [377]:
df_copy.sort_values('country', inplace=True)

## sort_index()

In [378]:
# we can sort DataFrame by index
df_copy.sort_index().head(3)

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
0,6417.0,i am student,1.0,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,...,NaN,NaN,NaN,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
1,74386.0,i am student,1.0,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Afghanistan,"Yes, part-time",Associate degree,"Information systems, information technology, o...",...,23.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy,Straight,Heterosexual
2,7085.0,i am student,1.0,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual

## nlargest()

In [379]:
# it will sort the n largest salary in ascending order
df_copy['convertedcomp'].nlargest(10)

# or
# --> df_copy.nlargest(10, 'convertedcomp')

10206    2000000.0
19063    2000000.0
28760    2000000.0
29739    2000000.0
30471    2000000.0
41142    2000000.0
42507    2000000.0
46930    2000000.0
52858    2000000.0
58715    2000000.0
Name: convertedcomp, dtype: float64

## nsmallest()

In [380]:
# sort it by decending order
df_copy['convertedcomp'].nsmallest(10)

3       0.0
15      0.0
162     0.0
913     0.0
2701    0.0
1635    0.0
3094    0.0
4167    0.0
5328    0.0
6392    0.0
Name: convertedcomp, dtype: float64

# cleaning data

## dropna()

In [381]:
# if will drop all the rows that contain null values

df_copy.dropna()

Empty DataFrame
Columns: [respondent, mainbranch, hobbyist, opensourcer, opensource, employment, country, student, edlevel, undergradmajor, eduother, orgsize, devtype, yearscode, age1stcode, yearscodepro, careersat, jobsat, mgridiot, mgrmoney, mgrwant, jobseek, lasthiredate, lastint, fizzbuzz, jobfactors, resumeupdate, currencysymbol, currencydesc, comptotal, compfreq, convertedcomp, workweekhrs, workplan, workchallenge, workremote, workloc, impsyn, coderev, coderevhrs, unittests, purchasehow, purchasewhat, languageworkedwith, languagedesirenextyear, databaseworkedwith, databasedesirenextyear, platformworkedwith, platformdesirenextyear, webframeworkedwith, webframedesirenextyear, misctechworkedwith, misctechdesirenextyear, devenviron, opsys, containers, blockchainorg, blockchainis, betterlife, itperson, offon, socialmedia, extraversion, screenname, sovisit1st, sovisitfreq, sovisitto, sofindanswer, sotimesaved, sohowmuchtime, soaccount, sopartfreq, sojobs, entteams, socomm, welcomechange, sonewcontent, age, gender, trans, sexuality, ethnicity, dependents, surveylength, surveyease, Straight, Homo]
Index: []

[0 rows x 87 columns]

In [382]:
# we can pass in the axis to either drop row or columns
# in blow clase all other column have missing values except 'main branch'

df_copy.dropna(axis=1)

             mainbranch
0          i am student
24         i am student
2          i am student
3          i am student
4          i am student
...                 ...
88880      i am student
88881      i am student
88882      i am student
88883  I am not student
88884  I am not student

[88885 rows x 1 columns]

In [383]:
# if we pass an parameter 'how=all' then it will drop only those row or column where all the values are missing from a row or column

df_copy.dropna(axis=1, how='all')

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
0,6417.0,i am student,1.0,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,...,NaN,NaN,NaN,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
24,43106.0,i am student,1.0,Never,"OSS is, on average, of LOWER quality than prop...",Employed part-time,Afghanistan,"Yes, part-time",Primary/elementary school,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7085.0,i am student,1.0,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
3,28638.0,i am student,1.0,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN,NaN,NaN
4,50767.0,i am student,0.0,Less than once per year,NaN,"Independent contractor, freelancer, or self-em...",Afghanistan,"Yes, part-time",Associate degree,"A health science (ex. nursing, pharmacy, radio...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88880,85744.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88062.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88601.0,i am student,0.0,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88883,NaN,I am not student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88884,NaN,I am not student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [384]:
# with paramater 'how=any' it will drop all the rows or column, where even a single values are missing

df_copy.dropna(axis=1, how='any')

             mainbranch
0          i am student
24         i am student
2          i am student
3          i am student
4          i am student
...                 ...
88880      i am student
88881      i am student
88882      i am student
88883  I am not student
88884  I am not student

[88885 rows x 1 columns]

In [385]:
# to drop some specific column , we can pass subset

# it will drop column hobbyist, if there is a missing values

df_copy.dropna(axis=0, how='any', subset=['hobbyist'])

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
0,6417.0,i am student,1.0,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,...,NaN,NaN,NaN,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
24,43106.0,i am student,1.0,Never,"OSS is, on average, of LOWER quality than prop...",Employed part-time,Afghanistan,"Yes, part-time",Primary/elementary school,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7085.0,i am student,1.0,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
3,28638.0,i am student,1.0,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN,NaN,NaN
4,50767.0,i am student,0.0,Less than once per year,NaN,"Independent contractor, freelancer, or self-em...",Afghanistan,"Yes, part-time",Associate degree,"A health science (ex. nursing, pharmacy, radio...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,73670.0,i am student,0.0,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88879,83648.0,i am student,0.0,Never,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,85744.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88062.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88601.0,i am student,0.0,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [386]:
# we can pass in multiple columns

df_copy.dropna(axis=0, how='any', subset=['hobbyist', 'country'])

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
0,6417.0,i am student,1.0,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,...,NaN,NaN,NaN,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
24,43106.0,i am student,1.0,Never,"OSS is, on average, of LOWER quality than prop...",Employed part-time,Afghanistan,"Yes, part-time",Primary/elementary school,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7085.0,i am student,1.0,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
3,28638.0,i am student,1.0,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN,NaN,NaN
4,50767.0,i am student,0.0,Less than once per year,NaN,"Independent contractor, freelancer, or self-em...",Afghanistan,"Yes, part-time",Associate degree,"A health science (ex. nursing, pharmacy, radio...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88745,66459.0,i am student,1.0,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Zimbabwe,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,29.0,Man,No,Straight / Heterosexual,Black or of African descent,Yes,Too long,Difficult,NaN,NaN
88746,76594.0,i am student,0.0,Never,The quality of OSS and closed source software ...,Employed full-time,Zimbabwe,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,33.0,Man,No,Straight / Heterosexual,Black or of African descent,Yes,Too long,Neither easy nor difficult,NaN,NaN
88747,82752.0,i am student,1.0,Never,The quality of OSS and closed source software ...,Employed full-time,Zimbabwe,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",...,33.0,Man,No,Straight / Heterosexual,Black or of African descent,Yes,Too long,Easy,NaN,NaN
88727,64719.0,i am student,1.0,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Zimbabwe,"Yes, full-time",Some college/university study without earning ...,Web development or web design,...,23.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Too long,Neither easy nor difficult,NaN,NaN
88750,57894.0,i am student,1.0,Less than once per year,NaN,NaN,Zimbabwe,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,21.0,Man,NaN,Straight / Heterosexual,Black or of African descent,No,Too long,Neither easy nor difficult,NaN,NaN

## replace()

In [387]:
# to repalce the custom missing values like 'na' or 'missing' or 'none'

df_copy.replace('na', np.NaN)

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
0,6417.0,i am student,1.0,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,...,NaN,NaN,NaN,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
24,43106.0,i am student,1.0,Never,"OSS is, on average, of LOWER quality than prop...",Employed part-time,Afghanistan,"Yes, part-time",Primary/elementary school,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7085.0,i am student,1.0,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult,Straight,Heterosexual
3,28638.0,i am student,1.0,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN,NaN,NaN
4,50767.0,i am student,0.0,Less than once per year,NaN,"Independent contractor, freelancer, or self-em...",Afghanistan,"Yes, part-time",Associate degree,"A health science (ex. nursing, pharmacy, radio...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88880,85744.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88062.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88601.0,i am student,0.0,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88883,NaN,I am not student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88884,NaN,I am not student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## isna()

In [388]:
# check if there is NaN values
# if it is NaN value then it will return true

df_copy.isna()

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
0,False,False,False,False,False,False,False,False,False,True,...,True,True,True,False,False,True,False,False,False,False
24,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,True,True,False,True,True,True
4,False,False,False,False,True,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88880,False,False,False,False,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
88881,False,False,False,False,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
88882,False,False,False,False,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
88883,True,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
88884,True,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

## fillna()

In [389]:
# fill the missing value with the desired value

df_copy.fillna(0).tail()

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease,Straight,Homo
88880,85744.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",0,0,0,0,0,...,0.0,0,0,0,0,0,0,0,0,0
88881,88062.0,i am student,0.0,Never,"OSS is, on average, of LOWER quality than prop...",0,0,0,0,0,...,0.0,0,0,0,0,0,0,0,0,0
88882,88601.0,i am student,0.0,Never,The quality of OSS and closed source software ...,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0,0,0
88883,0.0,I am not student,0.0,0,0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0,0,0
88884,0.0,I am not student,0.0,0,0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0,0,0

## na_values()

In [391]:
# changing na or missing values while loading data

replace_na_values = ['NA', 'missing']
df_copy = pd.read_csv('data/survey_results_public.csv', na_values=replace_na_values)

In [394]:
# fillna for the specific column

df_copy.loc[0:, 'OpenSourcer'].fillna('MISSING', inplace=True)

In [392]:
df_copy

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

## astype()

In [ ]:
df_copy['age'] = df_copy['age'].astype(float)